### ISSUE TITLE
X and Y tvel 

### ISSUE THREAD

**Issue by jaakobus** [Safarte/DockingAlignmentDisplay#1]
Could you separate tvel in x and y because the arrow is barely visible?
Otherwise i love this mod thank you for your work

**Comment by Safarte** [comment]
I agree that the current representation of tangent velocity is not easy to read, I was thinking of a way to split it into two marks like so:
![image](https://github.com/Safarte/DockingAlignmentDisplay/assets/46403615/98dc6749-7e1b-4dcb-b230-274376fdd6d3)
What would you think about this representation?

**Comment by jaakobus** [comment]
Looks really good but could you add numbers to this. And also could you make a more precise mode for the offset bars? Thank you in advance

**Comment by Safarte** [comment]
The total tangent velocity is already listed as a number at the bottom of the screen, I am not entirely sure separating it into X and Y components would give much more info than the indicators + total value.
Regarding precise offset, did you test the logarithmic scale mode (available in the mods settings)?

**Comment by jaakobus** [comment]
probably not xD. Thank you

**Comment by Safarte** [comment]
Let's leave this open until I implement the new tvel visual indicator ahah
